package com.utils

import com.example.healthychild.R

object GroupsUtils {

    const val health_one_img = R.drawable.health_one_img
    const val health_one_title =
        "Chaqaloq kindigini parvarishlash — vositalar, artish qoidalari, tavsiyalar"
    const val health_one_article =
        "Chaqaloq kindigi — bu go’dakni bachadondagi hayoti davomida ona bilan bog’lab turuvchi a’zodir. Tug’ruqdan so’ng shifokorlar kindik naychasini kesib tashlashadi va agar bu onaga ta’sir qilmasa-da, bolada alohida parvarishni talab qiladigan bitmagan yara qoladi." +
                "Bugungi kunda zamonaviy shifokorlar kindik naychasini kesib, uni tibbiy qisqich yordamida qisib qo’yadigan kichik bir uchini qoldirishadi. 4-7 kundan so’ng kindikning bu qismi tabiiy ravishda qurib uziladi. Shundan so’ng kindikning joyida parvarishni talab qiladigan yara hosil bo’ladi.\n" +
                "\n" +
                "Agar chaqaloq parvarishining barcha qoidalariga rioya qilinsa, uning kindigi 10-12 kunga kelib tuzalib ketadi. Ammo agar tegishli parvarish qilish e’tiborsiz qoldirilsa yoki noto’g’ri amalga oshirilsa, yara joyiga infektsiya tushishi xavfi paydo bo’ladi." +
                "\nChaqaloq tug’ilgandan bir necha daqiqa o’tgach shifokorlar kindik naychasini kesib, unga dezinfektsiyalash vositasi bilan ishlov berib, maxsus qisqich bilan qisib qo’yishadi. Tug’ruqxonada kindikni parvarishlash pediatr tomonidan amalga oshiriladi." +
                "\nAgar bu chaqaloq onaning birinchi farzandi bo’lsa, shifokor qanday muoalajalar qilayotganini kuzatish tavsiya etiladi, chunki tez orada ona bunday muolajani muntazam va mustaqil ravishda bajarishi lozim bo’ladi." +
                "\nBa’zida bola kindigi tug’ruqxonadan javob berishgacha muddat ichida mumiyolanishga ulguradi. Ammo bu chaqaloqning xususiyatlariga bog’liq va agar kindik qalinlashgan bo’lsa, unda ajralish jarayoni ham ko’proq vaqt talab etadi." +
                "\nKindik yarasi chaqaloqning zaif joyidir, unga infektsiya tushib qolmasligi, shuningdek, chaqaloqqa noqulaylik tug’dirmasligi uchun malakali parvarish zarur." +
                "\nPediatrlar kindikni quyidagi vositalar bilan parvarishlashni tavsiya etadilar:\n" +
                "\nVodorod peroksid (3% eritma);" +
                "\nSpirtli suv eritmasi (1% li brilliant yashili yoxud zelyonkadan foydalanish);"

const val ggg = "\nShokka tushiradigan dalil - bola qisqa vaqt ichida atigi bir necha santimetrli suvda ham tiqilib qolishi mumkin. Agar gap suv haqida ketganida har doim kuzatuv talab etiladi.\nYana bitta shokka soladigan dalil - choʻkib ketish 5 yoshgacha boʻlgan bolalar oʻlimining ahamiyati boʻyicha uchinchi sababchisi hisoblanadi.\nBasseyn\nBola suvda boʻlsa har doim nazorat ostida boʻlishi kerak.\nKatta bolalari uka yoki singillariga qarashga qoldirmaslik kerak.\nBolangizni suv bilan tanishtiring- u oʻziga boʻlgan ishonchga ega boʻlishi uchun uni chaqaloqlar uchun suv sporti turi boʻyicha mashgʻulotlarga olib boring.\nBaseyiningizni toʻsib qoʻying- basseyindagi devor su va bolangiz oʻrtasidagi toʻsiq sifatida zarur.\nShishiradigan oʻyinchoqlar qutqaruvchi moslama hisoblanmaydi va bolangizning xavfsizligini taʼminlamaydi.\nBasseyn yoki choʻmilish zonasining yonida elektr uzatish liniyalari yoki boshqa elektr jihozlar yoʻqligiga ishonch hosil qiling.\nBola suvda boʻlganida oddiy tagliklarni kiydirmaslik kerak, ular nam boʻlib, ogʻirlashib ketishi mumkin. \"Huggies® Little Swimmers\" kabi maxsuslashtirilgan mahsulotdan foydalaning.\nSuvning chuqurligi belgilanganligiga ishonch hosil qiling va suvga sakraganingizda yoki shoʻngʻiganingizda ehtiyot boʻling.\nOqshomlar va yigʻilishlar paytida chalkashlik boʻlmasligi uchun bolalarga qaraydigan odamni tayinlab qoʻyish kerak. Agar bu odam ketishi kerak boʻlsa, boshqa odamni tayinlang.\nBolalar baseyinlarini bogʻda qoldirmang.\nTelefon qoʻngʻirogʻiga javob berish uchun yoki boshqa sabablarga koʻra hech qachon bolani oʻzini basseynning oldida qoldirmang, hattoki bir necha daqiqalarga ham.\nBasseyn atrofidagi bolalarni kuzatayotganingizda oʻzingiz chalgʻishingizga yoʻl qoʻymang.\nBolaga sunʼiy nafas berishni oʻrganing- samarali birinchi yordam koʻrsatib, hayotini darhol saqlab qolish mumkin.\nBolangiz tegishli yoshga toʻlishi bilan uni suzishga olib boring.\n"
const val dd = "\\nShokka tushiradigan dalil - bola qisqa vaqt ichida atigi bir necha santimetrli suvda ham tiqilib qolishi mumkin. Agar gap suv haqida ketganida har doim kuzatuv talab etiladi.\\nYana bitta shokka soladigan dalil - choʻkib ketish 5 yoshgacha boʻlgan bolalar oʻlimining\n" +
        "ahamiyati boʻyicha uchinchi sababchisi hisoblanadi.\\nBasseyn\\nBola suvda boʻlsa har doim nazorat ostida boʻlishi kerak.\\nKatta bolalari uka yoki singillariga qarashga qoldirmaslik kerak.\\nBolangizni suv bilan tanishtiring- u oʻziga boʻlgan ishonchga ega boʻlishi uchun uni chaqaloqlar uchun suv sporti turi boʻyicha mashgʻulotlarga olib boring.\\nBaseyiningizni toʻsib qoʻying- basseyindagi devor su va bolangiz oʻrtasidagi toʻsiq sifatida zarur.\\nShishiradigan oʻyinchoqlar qutqaruvchi moslama hisoblanmaydi va bolangizning xavfsizligini taʼminlamaydi.\\nBasseyn yoki choʻmilish zonasining yonida elektr uzatish liniyalari yoki boshqa elektr jihozlar yoʻqligiga ishonch hosil qiling.\\nBola suvda boʻlganida oddiy tagliklarni kiydirmaslik kerak, ular nam boʻlib, ogʻirlashib ketishi mumkin. \"Huggies® Little Swimmers\" kabi maxsuslashtirilgan mahsulotdan foydalaning.\\nSuvning chuqurligi belgilanganligiga ishonch hosil qiling va suvga sakraganingizda yoki shoʻngʻiganingizda ehtiyot boʻling.\\nOqshomlar va yigʻilishlar paytida chalkashlik boʻlmasligi uchun bolalarga qaraydigan odamni tayinlab qoʻyish kerak. Agar bu odam ketishi kerak boʻlsa, boshqa odamni tayinlang.\\nBolalar baseyinlarini bogʻda qoldirmang.\\nTelefon qoʻngʻirogʻiga javob berish uchun yoki boshqa sabablarga koʻra hech qachon bolani oʻzini basseynning oldida qoldirmang, hattoki bir necha daqiqalarga ham.\\nBasseyn atrofidagi bolalarni kuzatayotganingizda oʻzingiz chalgʻishingizga yoʻl qoʻymang.\\nBolaga sunʼiy nafas berishni oʻrganing- samarali birinchi yordam koʻrsatib, hayotini darhol saqlab qolish mumkin.\\nBolangiz tegishli yoshga toʻlishi bilan uni suzishga olib boring.\n"
    const val pregnancy = "Amerikalik tadqiqotchilar Wi-Fi va mobil telefonlardan foydalanish farzand kutayotgan ayollarda homilaning nobud bo‘lish xavfini taxminan 50 foizga oshiradi degan xulosaga kelishdi. Mutaxassislarning so‘zlariga ko‘ra, qurilmalarning homilador ayollar organizmiga salbiy ta’siri sababi magnit maydonining nurlanishidadir. \n" +
            "\n" +
            "AQSh hududida o‘tkazilgan tadqiqot davomida homilasini yo‘qotgan ayollarning taxminan yarmi doimiy ravishda smartfondan foydalangani aniqlandi. Telefon tarmoqni izlash davomida tegishli jihozlar tomonidan qayd etilmaydigan past kuchlanishli radiatsion maydonni hosil qiladi. U butun organizm faoliyatiga ta’sir ko‘rsatadi.\n" +
            "\n" +
            "\"Homila tushishi AQShdagi homiladorlik holatlarining 15-20 foizida kuzatiladi. Bu jahon miqyosidagi muammo hisoblanadi, zero bunday ko‘rsatkichlar butun sayyorada qayd etilmoqda. Bo‘lg‘usi onani homilaning nobud bo‘lishi va boshqa tahdidlardan xavfsizlantirish uchun nafaqat u smartfon va boshqa portativ gadjetlardan foydalanishdan voz kechishi, balki yaqin atrofidagi kishilardan ham shuni so‘rashi kerak\", - deyishmoqda tadqiqotchilar. Olimlarning fikricha, bunday ta’sirdan boshqa yo‘llar bilan qutulishning iloji yo‘q. \n"

}